
[target.aarch64-apple-darwin]
image = "ghcr.io/cross-rs/aarch64-apple-darwin-cross-cross:local"
[target.aarch64_be-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64_be-unknown-linux-gnu-cross-cross:local"
[target.aarch64-linux-android]
image = "ghcr.io/cross-rs/aarch64-linux-android-cross:local"
[target.aarch64-pc-windows-msvc]
image = "ghcr.io/cross-rs/aarch64-pc-windows-msvc-cross-cross:local"
[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu-cross:local"
[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl-cross:local"
[target.arm-linux-androideabi]
image = "ghcr.io/cross-rs/arm-linux-androideabi-cross:local"
[target.arm-unknown-linux-gnueabi]
image = "ghcr.io/cross-rs/arm-unknown-linux-gnueabi-cross:local"
[target.arm-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/arm-unknown-linux-gnueabihf-cross:local"
[target.arm-unknown-linux-musleabi]
image = "ghcr.io/cross-rs/arm-unknown-linux-musleabi-cross:local"
[target.arm-unknown-linux-musleabihf]
image = "ghcr.io/cross-rs/arm-unknown-linux-musleabihf-cross:local"
[target.armv5te-unknown-linux-gnueabi]
image = "ghcr.io/cross-rs/armv5te-unknown-linux-gnueabi-cross:local"
[target.armv5te-unknown-linux-musleabi]
image = "ghcr.io/cross-rs/armv5te-unknown-linux-musleabi-cross:local"
[target.armv7-linux-androideabi]
image = "ghcr.io/cross-rs/armv7-linux-androideabi-cross:local"
[target.armv7-unknown-linux-gnueabi]
image = "ghcr.io/cross-rs/armv7-unknown-linux-gnueabi-cross:local"
[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf-cross:local"
[target.armv7-unknown-linux-musleabi]
image = "ghcr.io/cross-rs/armv7-unknown-linux-musleabi-cross:local"
[target.armv7-unknown-linux-musleabihf]
image = "ghcr.io/cross-rs/armv7-unknown-linux-musleabihf-cross:local"
[target.i586-unknown-linux-gnu]
image = "ghcr.io/cross-rs/i586-unknown-linux-gnu-cross:local"
[target.i586-unknown-linux-musl]
image = "ghcr.io/cross-rs/i586-unknown-linux-musl-cross:local"
[target.i686-apple-darwin]
image = "ghcr.io/cross-rs/i686-apple-darwin-cross-cross:local"
[target.i686-linux-android]
image = "ghcr.io/cross-rs/i686-linux-android-cross:local"
[target.i686-pc-windows-gnu]
image = "ghcr.io/cross-rs/i686-pc-windows-gnu-cross:local"
[target.i686-pc-windows-msvc]
image = "ghcr.io/cross-rs/i686-pc-windows-msvc-cross-cross:local"
[target.i686-unknown-freebsd]
image = "ghcr.io/cross-rs/i686-unknown-freebsd-cross:local"
[target.i686-unknown-linux-gnu]
image = "ghcr.io/cross-rs/i686-unknown-linux-gnu-cross:local"
[target.loongarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/loongarch64-unknown-linux-gnu-cross:local"
[target.mips64el-unknown-linux-gnuabi64]
image = "ghcr.io/cross-rs/mips64el-unknown-linux-gnuabi64-cross:local"
[target.mips64el-unknown-linux-muslabi64]
image = "ghcr.io/cross-rs/mips64el-unknown-linux-muslabi64-cross:local"
[target.mips64-unknown-linux-gnuabi64]
image = "ghcr.io/cross-rs/mips64-unknown-linux-gnuabi64-cross:local"
[target.mips64-unknown-linux-muslabi64]
image = "ghcr.io/cross-rs/mips64-unknown-linux-muslabi64-cross:local"
[target.mipsel-unknown-linux-gnu]
image = "ghcr.io/cross-rs/mipsel-unknown-linux-gnu-cross:local"
[target.mipsel-unknown-linux-musl]
image = "ghcr.io/cross-rs/mipsel-unknown-linux-musl-cross:local"
[target.mips-unknown-linux-gnu]
image = "ghcr.io/cross-rs/mips-unknown-linux-gnu-cross:local"
[target.mips-unknown-linux-musl]
image = "ghcr.io/cross-rs/mips-unknown-linux-musl-cross:local"
[target.powerpc64le-unknown-linux-gnu]
image = "ghcr.io/cross-rs/powerpc64le-unknown-linux-gnu-cross:local"
[target.powerpc64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/powerpc64-unknown-linux-gnu-cross:local"
[target.powerpc-unknown-linux-gnu]
image = "ghcr.io/cross-rs/powerpc-unknown-linux-gnu-cross:local"
[target.riscv64gc-unknown-linux-gnu]
image = "ghcr.io/cross-rs/riscv64gc-unknown-linux-gnu-cross:local"
[target.s390x-unknown-linux-gnu]
image = "ghcr.io/cross-rs/s390x-unknown-linux-gnu-cross:local"
[target.sparc64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/sparc64-unknown-linux-gnu-cross:local"
[target.sparcv9-sun-solaris]
image = "ghcr.io/cross-rs/sparcv9-sun-solaris-cross:local"
[target.thumbv6m-none-eabi]
image = "ghcr.io/cross-rs/thumbv6m-none-eabi-cross:local"
[target.thumbv7em-none-eabi]
image = "ghcr.io/cross-rs/thumbv7em-none-eabi-cross:local"
[target.thumbv7em-none-eabihf]
image = "ghcr.io/cross-rs/thumbv7em-none-eabihf-cross:local"
[target.thumbv7m-none-eabi]
image = "ghcr.io/cross-rs/thumbv7m-none-eabi-cross:local"
[target.thumbv7neon-linux-androideabi]
image = "ghcr.io/cross-rs/thumbv7neon-linux-androideabi-cross:local"
[target.thumbv7neon-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/thumbv7neon-unknown-linux-gnueabihf-cross:local"
[target.thumbv8m.base-none-eabi]
image = "ghcr.io/cross-rs/thumbv8m.base-none-eabi-cross:local"
[target.thumbv8m.main-none-eabi]
image = "ghcr.io/cross-rs/thumbv8m.main-none-eabi-cross:local"
[target.thumbv8m.main-none-eabihf]
image = "ghcr.io/cross-rs/thumbv8m.main-none-eabihf-cross:local"
[target.wasm32-unknown-emscripten]
image = "ghcr.io/cross-rs/wasm32-unknown-emscripten-cross:local"
[target.x86_64-apple-darwin]
image = "ghcr.io/cross-rs/x86_64-apple-darwin-cross-cross:local"
[target.x86_64-linux-android]
image = "ghcr.io/cross-rs/x86_64-linux-android-cross:local"
[target.x86_64-pc-windows-gnu]
image = "ghcr.io/cross-rs/x86_64-pc-windows-gnu-cross:local"
[target.x86_64-pc-windows-msvc]
image = "ghcr.io/cross-rs/x86_64-pc-windows-msvc-cross-cross:local"
[target.x86_64-sun-solaris]
image = "ghcr.io/cross-rs/x86_64-sun-solaris-cross:local"
[target.x86_64-unknown-dragonfly]
image = "ghcr.io/cross-rs/x86_64-unknown-dragonfly-cross:local"
[target.x86_64-unknown-freebsd]
image = "ghcr.io/cross-rs/x86_64-unknown-freebsd-cross:local"
[target.x86_64-unknown-illumos]
image = "ghcr.io/cross-rs/x86_64-unknown-illumos-cross:local"
[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu-cross:local"
[target.x86_64-unknown-linux-gnu-sde]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu-sde-cross-cross:local"
[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl-cross:local"
[target.x86_64-unknown-netbsd]
image = "ghcr.io/cross-rs/x86_64-unknown-netbsd-cross:local"
